# Generated by Django 4.2.1 on 2023-05-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TruckModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_capacity', models.PositiveSmallIntegerField()),
                ('sku', models.CharField(blank=True, max_length=5, unique=True)),
            ],
        ),
    ]
