# Generated by Django 4.2.1 on 2023-05-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0002_truckmodeltest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckmodeltest',
            name='zip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
