# Generated by Django 4.2.1 on 2023-05-24 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0004_remove_truckmodeltest_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TruckModel',
        ),
    ]
