# Generated by Django 4.2.1 on 2023-05-24 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0005_delete_truckmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TruckModelTest',
            new_name='TruckModel',
        ),
    ]
