# Generated by Django 4.2.1 on 2023-05-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_mol'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asd', models.CharField(max_length=155)),
                ('sdf', models.CharField(max_length=155)),
                ('fffd', models.PositiveSmallIntegerField()),
                ('dessddssdscription', models.TextField()),
            ],
        ),
    ]
