# Generated by Django 4.2.1 on 2023-05-24 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_cargomodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargomodel',
            old_name='asd',
            new_name='delivery',
        ),
        migrations.RenameField(
            model_name='cargomodel',
            old_name='dessddssdscription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='cargomodel',
            old_name='sdf',
            new_name='pick_up',
        ),
        migrations.RenameField(
            model_name='cargomodel',
            old_name='fffd',
            new_name='weight',
        ),
    ]
