# Generated by Django 4.2.1 on 2023-05-24 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0004_rename_asd_cargomodel_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mol',
            name='asdd',
        ),
        migrations.DeleteModel(
            name='Trr',
        ),
        migrations.DeleteModel(
            name='Cdd',
        ),
        migrations.DeleteModel(
            name='Mol',
        ),
    ]
