# Generated by Django 4.2.1 on 2023-05-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0005_remove_mol_asdd_delete_trr_delete_cdd_delete_mol'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoModelTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('pick_up', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
