# Generated by Django 4.2.1 on 2023-05-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0006_cargomodeltest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoModeTEstTEst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('zip_code', models.CharField(max_length=10)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pick_up', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
