# Generated by Django 4.2.1 on 2023-05-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0007_cargomodetesttest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargomodetesttest',
            name='pick_up',
            field=models.BooleanField(default=False),
        ),
    ]
