# Generated by Django 4.2.1 on 2023-05-24 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0009_rename_city_cargomodetesttest_city_delivery_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CargoModel',
        ),
        migrations.DeleteModel(
            name='CargoModelTest',
        ),
    ]
