# Generated by Django 4.2.1 on 2023-05-24 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0010_delete_cargomodel_delete_cargomodeltest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CargoModeTEstTEst',
            new_name='CargoModel',
        ),
    ]
